/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import clases.Archivo;
import java.awt.Image;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Jaime Suarez
 */
public class frmPrincipal extends javax.swing.JFrame {

    int personas = 1;
    double incremento = 0;
    int contarMusical = 0;
    int contarFamiliar = 0;
    double total = 0;
    double sumaTotal = 0; 
     double totalC = 0;
    double sumaTotalC = 0; 
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        ImageIcon imagen=new ImageIcon("src/imagenes/Puntos.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_DEFAULT));
        lblLogo.setIcon(icono);
        this.repaint();
        
    }
DefaultTableModel modelo=new DefaultTableModel();
DefaultTableModel modeloVenta=new DefaultTableModel();

 private void buscar(String cod){
        Archivo archivo=new Archivo();
        archivo.buscar(cod);
        if(archivo.getEncontro()){
            lblNombre.setText(archivo.getNombre());
            
            lblTipo.setText(archivo.getTipo());
            lblPrecio.setText(archivo.getPrecio());
            
           
            
            
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Contenedor = new javax.swing.JTabbedPane();
        pnlListaEventos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        pnlRegistrar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        pnlListaVentas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        btnListaVenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblPersonas = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMusical = new javax.swing.JLabel();
        lblFamiliar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalRecaudo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        lblCantidadBoletas = new javax.swing.JLabel();
        lblPromMusical = new javax.swing.JLabel();
        lblPromFamiliar = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Coqueta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(53, 53, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBorder(javax.swing.BorderFactory.createTitledBorder("La Coqueta"));

        pnlListaEventos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Eventos"));
        pnlListaEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEventos);

        pnlListaEventos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 440, 250));

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-list-40.png"))); // NOI18N
        btnListar.setToolTipText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        pnlListaEventos.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 50, -1));

        Contenedor.addTab("Lista Eventos", pnlListaEventos);

        pnlRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar"));
        pnlRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-look-for-40.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlRegistrar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 20, 50, 40));

        txtCodigo.setToolTipText("Codigo del Evento");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        pnlRegistrar.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, -1));

        jLabel1.setText("Código");
        pnlRegistrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, -1));

        jLabel2.setText("Nombre");
        pnlRegistrar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblNombre.setBackground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("-");
        pnlRegistrar.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 120, 20));

        jLabel3.setText("Tipo");
        pnlRegistrar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblTipo.setText("-");
        pnlRegistrar.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, -1));

        jLabel4.setText("Precio");
        pnlRegistrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblPrecio.setText("0");
        pnlRegistrar.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, -1));

        jLabel5.setText("Cantidad");
        pnlRegistrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtCantidad.setToolTipText("Solo Números");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        pnlRegistrar.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 50, -1));

        seleccion.add(jRadioButton1);
        jRadioButton1.setText("Diurno");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jRadioButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton1KeyPressed(evt);
            }
        });
        pnlRegistrar.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        seleccion.add(jRadioButton2);
        jRadioButton2.setText("Nocturno");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        pnlRegistrar.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTotal.setText("0");
        pnlRegistrar.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total");
        pnlRegistrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, -1));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-calculate-40.png"))); // NOI18N
        btnCalcular.setToolTipText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlRegistrar.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 50, -1));

        Contenedor.addTab("Registrar Venta", pnlRegistrar);

        jPanel2.setPreferredSize(new java.awt.Dimension(520, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVenta.setPreferredSize(new java.awt.Dimension(520, 240));
        jScrollPane2.setViewportView(tblVenta);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 250));

        btnListaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-list-40.png"))); // NOI18N
        btnListaVenta.setToolTipText("Lista Ventas");
        btnListaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnListaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 50, -1));

        pnlListaVentas.add(jPanel2);

        Contenedor.addTab("Lista Ventas", pnlListaVentas);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Número de personas:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        lblPersonas.setText("0");
        jPanel3.add(lblPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 70, -1));

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-estadísticas-40.png"))); // NOI18N
        btnEstadisticas.setToolTipText("Estadisticas");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        jPanel3.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel8.setText("Número de personas que compraron boletas 'Musical':");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setText("Número de personas que compraron boletas 'Familiar':");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblMusical.setText("0");
        jPanel3.add(lblMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 30, 20));

        lblFamiliar.setText("0");
        jPanel3.add(lblFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 30, -1));

        jLabel10.setText("Promedio de Ventas:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblPromedio.setText("0");
        jPanel3.add(lblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total Recaudado:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblTotalRecaudo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRecaudo.setText("0");
        jPanel3.add(lblTotalRecaudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 160, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 370, 10));

        jLabel12.setText("Total Boletas:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblCantidadBoletas.setText("0");
        jPanel3.add(lblCantidadBoletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, -1));

        lblPromMusical.setText("0");
        jPanel3.add(lblPromMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 70, -1));

        lblPromFamiliar.setText("0");
        jPanel3.add(lblPromFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 80, -1));

        Contenedor.addTab("Historico", jPanel3);

        jPanel1.add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 570, 380));
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 580, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
             Archivo archivo=new Archivo();
        List<String[]> listado=archivo.listado();
        
        //agregar los datos al modelo
        if(!listado.isEmpty()){
            modelo.setRowCount(0);//limpiar la tabla
            
            //crear los encabezados
            String[] encabezado={"Codigo Evento","Nombre","Tipo","precio"};
            modelo.setColumnIdentifiers(encabezado);
            
            //asignar el modelo a la tabla
            tblEventos.setModel(modelo);
            //agregar las filas del archivo
            for (int i = 0; i < listado.size(); i++) {
                modelo.addRow(listado.get(i));
            }
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         buscar(txtCodigo.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
          int tecla=evt.getKeyChar();
        boolean numeros = tecla>=48 && tecla<=57;
        if(!numeros){
            evt.consume();}
        if(txtCodigo.getText().length()>=2){
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
          int tecla=evt.getKeyChar();
        boolean numeros = tecla>=48 && tecla<=57;
        if(!numeros){
            evt.consume();}
        if(txtCantidad.getText().length()>=2){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        incremento = Double.parseDouble(lblPrecio.getText());
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
       
         if(lblTipo.getText().equals("familiar")){
        incremento = Double.parseDouble(lblPrecio.getText())*1.15;
        }else{
             incremento = Double.parseDouble(lblPrecio.getText())*1.25;
         }
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if(txtCantidad.getText().equals("")){
        lblTotal.setText("0");
        }
        else{
             lblTotal.setText(String.valueOf(Double.parseDouble(txtCantidad.getText()) * incremento) );
        }
         Archivo archivo = new Archivo();
        archivo.escribir(txtCodigo.getText(),lblNombre.getText(),lblTipo.getText(),lblPrecio.getText() ,txtCantidad.getText(),lblTotal.getText()); 
    
        txtCodigo.setText("");
        lblNombre.setText("");
        lblTipo.setText("");
        lblPrecio.setText("");
        txtCantidad.setText("");
        lblTotal.setText("");
       
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jRadioButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton1KeyPressed
        // TODO add your handling code here:
        incremento = Double.parseDouble(lblPrecio.getText());
    }//GEN-LAST:event_jRadioButton1KeyPressed

    private void btnListaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaVentaActionPerformed
        // TODO add your handling code here:
                  Archivo archivo=new Archivo();
        List<String[]> listadoVentas=archivo.listadoVentas();
        
        //agregar los datos al modelo
        if(!listadoVentas.isEmpty()){
            modeloVenta.setRowCount(0);//limpiar la tabla
            
            //crear los encabezados
            String[] encabezado={"Codigo Evento","Nombre","Tipo","precio","Cantidad","Total"};
            modeloVenta.setColumnIdentifiers(encabezado);
            
            //asignar el modelo a la tabla
            tblVenta.setModel(modeloVenta);
            //agregar las filas del archivo
            personas=listadoVentas.size();
            for (int i = 0; i < listadoVentas.size(); i++) {
                modeloVenta.addRow(listadoVentas.get(i));
            }
            
            
              List<String[]> datosVentas = archivo.listadoVentas();    

    for (String[] fila : datosVentas) {
        if (fila.length >= 6) {
            String can = fila[4].trim();
            String totalStr = fila[5].trim();

              try {
                 totalC = Double.parseDouble(can);
                sumaTotalC += totalC;
            } catch (NumberFormatException e) {
                System.out.println("Error al convertir a número: " + totalStr);
            }
       

            try {
                 total = Double.parseDouble(totalStr);
                sumaTotal += total;
            } catch (NumberFormatException e) {
                System.out.println("Error al convertir a número: " + can);
            }
        }
    }
            
            
              
        int columnIndexTipo = 2; // La columna "Tipo" es la tercera (índice 2)
        
        for (int i = 0; i < modeloVenta.getRowCount(); i++) {
            String tipo = (String) modeloVenta.getValueAt(i, columnIndexTipo);
            if ("musical".equalsIgnoreCase(tipo)) {
                contarMusical++;
            }
             if ("familiar".equalsIgnoreCase(tipo)) {
                contarFamiliar++;
            }
        }
        
     
        
        }
    }//GEN-LAST:event_btnListaVentaActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        // TODO add your handling code here:
        /**
        lblPersonas.setText(String.valueOf(personas) );
        lblMusical.setText(String.valueOf(contarMusical));
        lblPromMusical.setText(String.valueOf(contarMusical/personas*100)+"%");
        lblFamiliar.setText(String.valueOf(contarFamiliar));
        lblPromFamiliar.setText(String.valueOf(contarFamiliar/personas*100)+"%");
        lblTotalRecaudo.setText(String.valueOf(sumaTotal));
        lblCantidadBoletas.setText(String.valueOf(sumaTotalC));
        lblPromedio.setText(String.valueOf(sumaTotalC/sumaTotal*100)+"%");*/
          NumberFormat formatoNumero = NumberFormat.getNumberInstance(Locale.US);
    NumberFormat formatoPorcentaje = NumberFormat.getPercentInstance(Locale.US);
    
  
    formatoPorcentaje.setMinimumFractionDigits(2);
    
   
    lblPersonas.setText(formatoNumero.format(personas));
    lblMusical.setText(formatoNumero.format(contarMusical));
    lblPromMusical.setText(formatoPorcentaje.format((double) contarMusical / personas));
    lblFamiliar.setText(formatoNumero.format(contarFamiliar));
    lblPromFamiliar.setText(formatoPorcentaje.format((double) contarFamiliar / personas));
    lblTotalRecaudo.setText("$" + formatoNumero.format(sumaTotal));
    lblCantidadBoletas.setText(formatoNumero.format(sumaTotalC));
    lblPromedio.setText("$"+formatoNumero.format((double)  sumaTotal/sumaTotalC ));

        
        
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Contenedor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnListaVenta;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantidadBoletas;
    private javax.swing.JLabel lblFamiliar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMusical;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPersonas;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPromFamiliar;
    private javax.swing.JLabel lblPromMusical;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalRecaudo;
    private javax.swing.JPanel pnlListaEventos;
    private javax.swing.JPanel pnlListaVentas;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.ButtonGroup seleccion;
    private javax.swing.JTable tblEventos;
    private javax.swing.JTable tblVenta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
